### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by TheWalkingFridge** [matthewfx/sleek_circular_slider#48]
Now that flutter released 2.0, I think most developers will upgrade. 
Would be nice to have this lib updated with null-safety so people using it can migrate.

**Comment by DanMossa** [comment]
This is currently the only package that I haven't been able to upgrade to support null-safety

**Comment by matthewfx** [comment]
Sorry, I'm too busy atm and don't have time to update it :(

**Comment by DanMossa** [comment]
@matthewfx Understandable!
I will say that this package may end up rotting then unless someone makes a PR :o

**Comment by TheWalkingFridge** [comment]
Made a quick PR #49

**Comment by matthewfx** [comment]
Sorry... I've been working very hard for the last couple of weeks and wasn't able to look into it. I see there are 2 PRs addressing the null safety. I promise to try to look into them this weekend. @TheWalkingFridge thank you for one of them! @DanMossa I'd suggest you should start making open source software by yourself. Then keep maintaining it so that it doesn't end up rotting. It is very easy to criticize someone who has spent lots of their private time building some and can't immediately jump and make updates...

**Comment by DanMossa** [comment]
@matthewfx Hey matthew!
I'd like to say sorry if my post came off rude. I genuinely didn't mean for that to be the way my words were portrayed. I 100% understand how hard it is to maintain code and I didn't mean to rush you at all!

**Comment by matthewfx** [comment]
@TheWalkingFridge I think all is good. Could you only please change the version number to 1.3.0 rather than 2.0.0?

**Comment by TheWalkingFridge** [comment]
Hi @matthewfx. Note, that I've been following the [official migration guidelines](https://dart.dev/null-safety/migration-guide). If you scroll down to step 5, you can see that migrating is considered a breaking change and the major version should be changed. That said, if you think we should keep it at 1.3.0, I'll be happy to change it.

**Comment by matthewfx** [comment]
I just published version 2.0.0. Thank you @TheWalkingFridge
