### ISSUE TITLE
Max value cant be more than initalValue

### ISSUE THREAD

**Issue by mariapapag95** [matthewfx/sleek_circular_slider#62]
For my purpose, I am trying to track time spent doing an activity. The max value of the ring is the total time the activity should take, but the user can take more than this time. I am setting initial value to the time user is taking, so that when the user has gone over the total time the activity should take (max value) I was expected the ring to start filling a second time, going over the max as shown in the mock up below. What can I change to make this possible?

<img width="711" alt="Screen Shot 2021-08-16 at 9 53 43 AM" src="https://user-images.githubusercontent.com/47039896/129574807-35a6353c-22db-48e6-a7d8-855f4d3fcc2f.png">

**Comment by matthewfx** [comment]
Hi Maria,

That's how Apple Fitness rings work. It is not possible with my library (it just goes full 360 degrees and starts again from 0). That would be pretty tricky to achieve. I reckon you could try adding a second ring when the value reaches 360 degrees above the first ring full ring because it has to cast a shadow on it. BTW Apple has patented their rings design and if the app you've been working on gains a lot of traction (fingers crossed) you might receive a letter from their lawyers ;) 

Good luck with it!

**Comment by mariapapag95** [comment]
Thanks! They're definitely the inspiration for this, so I will keep that in mind moving forward.
